import "server-only";

import type { CommunityItem, PopupBanner } from "@/lib/reverseclinic-types";

const mockAuthor = "리버스클리닉";

function image(src: string, alt: string, caption?: string) {
  return { src, alt, caption };
}

function textBlock(id: string, heading: string, body: string) {
  return {
    id,
    type: "text" as const,
    heading,
    body,
  };
}

function imageBlock(
  id: string,
  heading: string,
  src: string,
  alt: string,
  body: string,
  caption?: string,
) {
  return {
    id,
    type: "image" as const,
    heading,
    image: image(src, alt, caption),
    body,
  };
}

function galleryBlock(
  id: string,
  heading: string,
  images: Array<{ src: string; alt: string; caption?: string }>,
  body?: string,
) {
  return {
    id,
    type: "gallery" as const,
    heading,
    images: images.map((item) => image(item.src, item.alt, item.caption)),
    body,
  };
}

export function normalizeUploadFileName(fileName: string) {
  const normalizedSave = fileName.replace(/\.(jpe?g|png|gif|webp|avif)\.save$/i, ".$1");
  const safeName = normalizedSave
    .normalize("NFKC")
    .replace(/[^\w.\-\u3131-\uD79D]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return safeName || "upload-image.jpg";
}

const reviewSeed = [
  {
    id: "reviews-1",
    title: "[인스타후기] 피코슈어 토닝 레이저(릴스)",
    summary: "피부 톤 개선과 잡티 완화를 중심으로 상담부터 애프터케어까지 정리한 후기입니다.",
    publishedAt: "2025-05-07T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 242,
    coverImage: "/reverseclinic-mirror/files/6ykpMK4Lc.webp",
    highlightImage: "/reverseclinic-mirror/site/reverseclinic.com/_files/6Bl1Y8wMi.webp",
  },
  {
    id: "reviews-2",
    title: "[강남점 대표원장님 직접시술] 여자 튠페이스 Before & After",
    summary: "대표원장 직접 시술 케이스의 변화 포인트와 회복 일정을 정리한 시술후기입니다.",
    publishedAt: "2025-04-23T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 328,
    coverImage: "/reverseclinic-mirror/files/6CxBA6fdd.webp",
    highlightImage: "/reverseclinic-mirror/files/6CxBLLCAU.webp",
  },
  {
    id: "reviews-3",
    title: "[강남점 대표원장님 직접시술] 남자 튠페이스 Before & After",
    summary: "남성 라인 개선 중심의 튠페이스 시술 흐름과 관리법을 한 번에 확인할 수 있습니다.",
    publishedAt: "2025-04-23T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 333,
    coverImage: "/reverseclinic-mirror/files/6CxByoDpl.webp",
    highlightImage: "/reverseclinic-mirror/files/6CxD8zirk.webp",
  },
  {
    id: "reviews-4",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "시술 직후 자극감, 회복 기간, 유지 팁까지 간단하게 정리한 인스타 후기입니다.",
    publishedAt: "2025-04-08T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 262,
    coverImage: "/reverseclinic-mirror/files/6tZ6XQ0Fj.webp",
    highlightImage: "/reverseclinic-mirror/files/6CxBIlQYw.webp",
  },
  {
    id: "reviews-5",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "색소 완화 프로그램을 반복 진행한 고객님의 경과를 정리한 후기입니다.",
    publishedAt: "2025-08-19T09:00:00.000Z",
    isPinned: false,
    displayNumber: 874,
    viewCount: 158,
    coverImage: "/reverseclinic-mirror/files/6tZ6ZrJOS.webp",
    highlightImage: "/reverseclinic-mirror/files/6AFzzURPh.webp",
  },
  {
    id: "reviews-6",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "토닝 레이저 중심의 주차별 경과와 재생 관리 루틴을 담았습니다.",
    publishedAt: "2025-08-11T09:00:00.000Z",
    isPinned: false,
    displayNumber: 873,
    viewCount: 227,
    coverImage: "/reverseclinic-mirror/files/6tZ6NDpGx.webp",
    highlightImage: "/reverseclinic-mirror/files/6AFzBtGhq.webp",
  },
  {
    id: "reviews-7",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "잡티와 전체 피부톤 개선을 목표로 진행한 피코슈어 케이스입니다.",
    publishedAt: "2025-07-18T09:00:00.000Z",
    isPinned: false,
    displayNumber: 872,
    viewCount: 164,
    coverImage: "/reverseclinic-mirror/files/6tZ6UGkzG.webp",
    highlightImage: "/reverseclinic-mirror/files/6AFzCcRgv.webp",
  },
  {
    id: "reviews-8",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "붉은기 완화와 피부 결 보정에 초점을 맞춘 토닝 레이저 후기입니다.",
    publishedAt: "2025-07-16T09:00:00.000Z",
    isPinned: false,
    displayNumber: 871,
    viewCount: 122,
    coverImage: "/reverseclinic-mirror/files/5U48UiGCc.webp",
    highlightImage: "/reverseclinic-mirror/files/6uCPF0hPk.webp",
  },
  {
    id: "reviews-9",
    title: "[인스타후기] 피코슈어 토닝 레이저 2차",
    summary: "2차 시술 이후 유지력과 피부광 변화를 비교한 피코슈어 후기입니다.",
    publishedAt: "2025-07-04T09:00:00.000Z",
    isPinned: false,
    displayNumber: 870,
    viewCount: 234,
    coverImage: "/reverseclinic-mirror/files/5U497NFOO.webp",
    highlightImage: "/reverseclinic-mirror/files/6uCPF0Owr.webp",
  },
  {
    id: "reviews-10",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "여름철 색소 고민이 심한 고객님의 토닝 레이저 진행 사례입니다.",
    publishedAt: "2025-06-23T09:00:00.000Z",
    isPinned: false,
    displayNumber: 869,
    viewCount: 131,
    coverImage: "/reverseclinic-mirror/files/5U4a5tm9M.webp",
    highlightImage: "/reverseclinic-mirror/files/6uCPF12IB.webp",
  },
  {
    id: "reviews-11",
    title: "[인스타후기] 큐오필",
    summary: "윤곽과 탄력을 함께 잡은 큐오필 프로그램의 상담 포인트를 정리했습니다.",
    publishedAt: "2025-04-10T09:00:00.000Z",
    isPinned: false,
    displayNumber: 868,
    viewCount: 199,
    coverImage: "/reverseclinic-mirror/files/5U4d6YPG5.webp",
    highlightImage: "/reverseclinic-mirror/files/6ACFCqqBH.webp",
  },
  {
    id: "reviews-12",
    title: "[인스타후기] 피코슈어 토닝 레이저",
    summary: "점차 완화되는 색소와 피부 결의 변화를 짧은 텍스트 중심으로 정리했습니다.",
    publishedAt: "2025-04-07T09:00:00.000Z",
    isPinned: false,
    displayNumber: 867,
    viewCount: 236,
    coverImage: "/reverseclinic-mirror/files/6cobB85Zk.webp",
    highlightImage: "/reverseclinic-mirror/files/6BYzN0e41.webp",
  },
];

const beforeAfterSeed = [
  {
    id: "before-after-1",
    category: "피부",
    title: "[안산점] 이중턱 지방분해 전/후",
    summary: "이중턱 라인 개선 전후",
    publishedAt: "2025-08-19T09:00:00.000Z",
    viewCount: 412,
    beforeImage: "/reverseclinic-mirror/files/6AFzzURPh.webp",
    afterImage: "/reverseclinic-mirror/files/6AFzBtGhq.webp",
  },
  {
    id: "before-after-2",
    category: "피부",
    title: "[안산점] 두상필러 전/후",
    summary: "두상필러 전후",
    publishedAt: "2025-08-11T09:00:00.000Z",
    viewCount: 398,
    beforeImage: "/reverseclinic-mirror/files/6AFzCcRgv.webp",
    afterImage: "/reverseclinic-mirror/files/6ACFCqqBH.webp",
  },
  {
    id: "before-after-3",
    category: "바디",
    title: "[안산점] 가슴필러 전/후",
    summary: "가슴필러 전후",
    publishedAt: "2025-07-24T09:00:00.000Z",
    viewCount: 287,
    beforeImage: "/reverseclinic-mirror/files/6Bl1Y8wMi.webp",
    afterImage: "/reverseclinic-mirror/files/6Bl1W9_zB.webp",
  },
  {
    id: "before-after-4",
    category: "쁘띠",
    title: "[안산점] 실리프팅 전/후",
    summary: "실리프팅 전후",
    publishedAt: "2025-07-18T09:00:00.000Z",
    viewCount: 366,
    beforeImage: "/reverseclinic-mirror/files/6CxBA6fdd.webp",
    afterImage: "/reverseclinic-mirror/files/6CxBA6fdd.webp",
  },
  {
    id: "before-after-5",
    category: "피부",
    title: "[안산점] 큐텐필 전/후",
    summary: "큐텐필 전후",
    publishedAt: "2025-07-12T09:00:00.000Z",
    viewCount: 244,
    beforeImage: "/reverseclinic-mirror/files/6CxBLLCAU.webp",
    afterImage: "/reverseclinic-mirror/files/6CxByoDpl.webp",
  },
  {
    id: "before-after-6",
    category: "피부",
    title: "[안산점] 리프팅핏 전/후",
    summary: "리프팅핏 전후",
    publishedAt: "2025-07-04T09:00:00.000Z",
    viewCount: 225,
    beforeImage: "/reverseclinic-mirror/files/6CxD8zirk.webp",
    afterImage: "/reverseclinic-mirror/files/6BYzN0e41.webp",
  },
  {
    id: "before-after-7",
    category: "바디",
    title: "[안산점] 어깨필러 전/후",
    summary: "어깨필러 전후",
    publishedAt: "2025-06-25T09:00:00.000Z",
    viewCount: 218,
    beforeImage: "/reverseclinic-mirror/files/6uCPE_6Ex.webp",
    afterImage: "/reverseclinic-mirror/files/6uCPE_vsh.webp",
  },
  {
    id: "before-after-8",
    category: "바디",
    title: "[안산점] 가슴필러 전/후",
    summary: "가슴필러 전후",
    publishedAt: "2025-06-20T09:00:00.000Z",
    viewCount: 233,
    beforeImage: "/reverseclinic-mirror/files/6uCPF0hPk.webp",
    afterImage: "/reverseclinic-mirror/files/6uCPF0Owr.webp",
  },
  {
    id: "before-after-9",
    category: "바디",
    title: "[안산점] 청담필러 전/후",
    summary: "청담필러 전후",
    publishedAt: "2025-06-13T09:00:00.000Z",
    viewCount: 175,
    beforeImage: "/reverseclinic-mirror/files/6uCPF12IB.webp",
    afterImage: "/reverseclinic-mirror/files/6AFzzURPh.webp",
  },
  {
    id: "before-after-10",
    category: "쁘띠",
    title: "[안산점] 청담필러 전/후",
    summary: "청담필러 전후",
    publishedAt: "2025-06-03T09:00:00.000Z",
    viewCount: 167,
    beforeImage: "/reverseclinic-mirror/files/6AFzBtGhq.webp",
    afterImage: "/reverseclinic-mirror/files/6AFzCcRgv.webp",
  },
  {
    id: "before-after-11",
    category: "피부",
    title: "[안산점] 쇄골필러 전/후",
    summary: "쇄골필러 전후",
    publishedAt: "2025-05-28T09:00:00.000Z",
    viewCount: 149,
    beforeImage: "/reverseclinic-mirror/files/6ACFCqqBH.webp",
    afterImage: "/reverseclinic-mirror/files/6Bl1Y8wMi.webp",
  },
  {
    id: "before-after-12",
    category: "쁘띠",
    title: "[안산점] 큐텐필 전/후",
    summary: "큐텐필 전후",
    publishedAt: "2025-05-19T09:00:00.000Z",
    viewCount: 155,
    beforeImage: "/reverseclinic-mirror/files/6CxBA6fdd.webp",
    afterImage: "/reverseclinic-mirror/files/6CxBLLCAU.webp",
  },
];

const mediaSeed = [
  {
    id: "media-in-1",
    title: "필러 시술 선택, 정확한 피부과적 진단 중요 [한재진 원장 칼럼]",
    summary: "미디어에 소개된 한재진 원장 칼럼의 핵심 내용을 정리했습니다.",
    publishedAt: "2023-07-27T09:00:00.000Z",
    displayNumber: 32,
    isPinned: false,
    viewCount: 417,
    coverImage: "/reverseclinic-mirror/files/6BueQ4Nyn.webp",
  },
  {
    id: "media-in-2",
    title: "피부 탄력 저하, 볼뉴머 리프팅 진행 시 주의점은",
    summary: "피부 탄력 저하 개선을 위한 리프팅 진행 시 체크 포인트를 정리한 기사입니다.",
    publishedAt: "2023-07-18T09:00:00.000Z",
    displayNumber: 31,
    isPinned: false,
    viewCount: 413,
    coverImage: "/reverseclinic-mirror/files/6CxByoDpl.webp",
  },
  {
    id: "media-in-3",
    title: "몸매 라인 교정 위한 바디필러 시술 주의사항은?",
    summary: "바디필러 시술 전 확인해야 할 기준과 상담 포인트를 담았습니다.",
    publishedAt: "2022-09-13T09:00:00.000Z",
    displayNumber: 30,
    isPinned: false,
    viewCount: 345,
    coverImage: "/reverseclinic-mirror/files/6CxD8zirk.webp",
  },
  {
    id: "media-in-4",
    title: "햇볕에 타고 늘어난 모공… 포텐자 등 시술 전 체크포인트",
    summary: "모공과 피부 결 개선을 위한 장비 선택 기준을 소개한 기사입니다.",
    publishedAt: "2022-08-24T09:00:00.000Z",
    displayNumber: 29,
    isPinned: false,
    viewCount: 393,
    coverImage: "/reverseclinic-mirror/files/6BYzN0e41.webp",
  },
  {
    id: "media-in-5",
    title: "리버스클리닉 새로운 대표모델 촬영현장 메이킹필름",
    summary: "리버스클리닉의 신규 메이킹필름 공개 소식을 전달합니다.",
    publishedAt: "2021-05-25T09:00:00.000Z",
    displayNumber: null,
    isPinned: true,
    viewCount: 789,
    coverImage: "/reverseclinic-mirror/files/6ACFCqqBH.webp",
  },
  {
    id: "media-in-6",
    title: "인모드+슈링크 체험단 맥심의 그녀 은유화 리얼후기",
    summary: "슈링크와 인모드 프로그램을 체험한 고객의 리얼후기를 정리했습니다.",
    publishedAt: "2020-12-04T09:00:00.000Z",
    displayNumber: null,
    isPinned: true,
    viewCount: 722,
    coverImage: "/reverseclinic-mirror/files/6Bl1W9_zB.webp",
  },
  {
    id: "media-in-7",
    title: "제모체험단, 레이저제모 리얼후기",
    summary: "제모 프로그램의 장점과 회복 일정을 다룬 체험단 콘텐츠입니다.",
    publishedAt: "2020-10-27T09:00:00.000Z",
    displayNumber: null,
    isPinned: true,
    viewCount: 764,
    coverImage: "/reverseclinic-mirror/files/6Bl1Y8wMi.webp",
  },
  {
    id: "media-in-8",
    title: "필러 시술 통한 외모 콤플렉스 개선… 주의할 점은?",
    summary: "필러 시술 전후 기대치와 상담 기준을 정리한 미디어 칼럼입니다.",
    publishedAt: "2020-09-28T09:00:00.000Z",
    displayNumber: 25,
    isPinned: false,
    viewCount: 390,
    coverImage: "/reverseclinic-mirror/files/6CxBLLCAU.webp",
  },
  {
    id: "media-in-9",
    title: "인모드 리프팅, 시술 전 꼭 알아야할 사항은? [김민수 원장 칼럼]",
    summary: "인모드 리프팅 시술 전 확인해야 할 개인별 상담 기준을 소개합니다.",
    publishedAt: "2020-08-04T09:00:00.000Z",
    displayNumber: 24,
    isPinned: false,
    viewCount: 367,
    coverImage: "/reverseclinic-mirror/files/6CxByoDpl.webp",
  },
  {
    id: "media-in-10",
    title: "안티에이징, 레이저 및 에너테스 통한 피부 관리",
    summary: "안티에이징 장비 선택과 병행 시술 원칙을 쉽게 정리한 기사입니다.",
    publishedAt: "2019-10-25T09:00:00.000Z",
    displayNumber: 23,
    isPinned: false,
    viewCount: 381,
    coverImage: "/reverseclinic-mirror/files/6CxD8zirk.webp",
  },
];

const noticeSeed = [
  {
    id: "notice-1",
    title: "8월 진료 일정 및 휴진 안내",
    summary: "광복절과 주말 진료 시간, 휴진 일정을 안내드립니다.",
    publishedAt: "2025-08-01T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 182,
  },
  {
    id: "notice-2",
    title: "전후사진 열람 정책 안내",
    summary: "전후사진 게시판 열람 시 로그인 정책과 주의사항을 안내드립니다.",
    publishedAt: "2025-07-09T09:00:00.000Z",
    isPinned: true,
    displayNumber: null,
    viewCount: 144,
  },
  {
    id: "notice-3",
    title: "홈페이지 커뮤니티 개편 안내",
    summary: "커뮤니티 게시판 구조와 열람 흐름이 개편되어 안내드립니다.",
    publishedAt: "2025-06-22T09:00:00.000Z",
    isPinned: false,
    displayNumber: 118,
    viewCount: 98,
  },
  {
    id: "notice-4",
    title: "온라인 상담 접수 처리 시간 안내",
    summary: "온라인 상담과 예약 접수의 처리 시간과 연락 기준을 정리했습니다.",
    publishedAt: "2025-06-10T09:00:00.000Z",
    isPinned: false,
    displayNumber: 117,
    viewCount: 86,
  },
  {
    id: "notice-5",
    title: "개인정보 처리방침 개정 안내",
    summary: "개인정보 처리방침과 동의 문구 일부가 개정되었습니다.",
    publishedAt: "2025-05-19T09:00:00.000Z",
    isPinned: false,
    displayNumber: 116,
    viewCount: 67,
  },
  {
    id: "notice-6",
    title: "카카오톡 상담 운영시간 변경 안내",
    summary: "카카오톡 상담 운영시간이 일부 조정되어 안내드립니다.",
    publishedAt: "2025-04-02T09:00:00.000Z",
    isPinned: false,
    displayNumber: 115,
    viewCount: 59,
  },
];

export function buildDefaultCommunityItems() {
  const reviewItems: CommunityItem[] = reviewSeed.map((item) => ({
    id: item.id,
    boardType: "reviews",
    title: item.title,
    summary: item.summary,
    author: mockAuthor,
    publishedAt: item.publishedAt,
    tags: ["시술후기", "강남점"],
    isPinned: item.isPinned,
    displayNumber: item.displayNumber,
    viewCount: item.viewCount,
    category: null,
    requiresLogin: true,
    coverImage: image(item.coverImage, item.title),
    blocks: [
      textBlock(
        `${item.id}-text-1`,
        "상담 내용",
        "피부 타입과 시술 이력, 기대하는 변화를 먼저 정리한 뒤 상담을 진행했습니다. 자극을 줄이면서도 톤과 결을 동시에 끌어올리는 방향으로 프로그램을 구성했습니다.",
      ),
      imageBlock(
        `${item.id}-image-1`,
        "시술 포인트",
        item.highlightImage,
        `${item.title} 대표 이미지`,
        "시술 직후에는 미세한 붉은기와 열감이 있었지만, 진정 관리 후 빠르게 일상 복귀가 가능했습니다. 개인차는 있으나 주차별로 피부 톤과 결의 차이가 점진적으로 보입니다.",
        "대표 이미지",
      ),
      textBlock(
        `${item.id}-text-2`,
        "애프터케어",
        "자외선 차단과 보습, 각질 자극을 줄이는 홈케어를 병행했고 2주 차부터 화장이 훨씬 자연스럽게 받는다는 피드백이 있었습니다.",
      ),
    ],
  }));

  const beforeAfterItems: CommunityItem[] = beforeAfterSeed.map((item, index) => ({
    id: item.id,
    boardType: "before-after",
    title: item.title,
    summary: item.summary,
    author: mockAuthor,
    publishedAt: item.publishedAt,
    tags: ["전후사진", item.category],
    isPinned: false,
    displayNumber: 300 - index,
    viewCount: item.viewCount,
    category: item.category,
    requiresLogin: true,
    coverImage: image(item.beforeImage, `${item.title} Before`),
    blocks: [
      galleryBlock(
        `${item.id}-gallery-1`,
        "Before & After",
        [
          { src: item.beforeImage, alt: `${item.title} Before`, caption: "Before" },
          { src: item.afterImage, alt: `${item.title} After`, caption: "After" },
        ],
        "개인별 피부 상태와 체형 차이에 따라 같은 결과를 보장할 수 없으며, 충분한 상담 후 시술 범위를 결정합니다.",
      ),
      textBlock(
        `${item.id}-text-1`,
        "안내",
        "전후사진 열람은 로그인 후 가능합니다. 상세 이미지는 상담 기록 및 회복 일정과 함께 확인할 수 있습니다.",
      ),
    ],
  }));

  const mediaItems: CommunityItem[] = mediaSeed.map((item) => ({
    id: item.id,
    boardType: "media-in",
    title: item.title,
    summary: item.summary,
    author: mockAuthor,
    publishedAt: item.publishedAt,
    tags: ["미디어 IN", "원장 칼럼"],
    isPinned: item.isPinned,
    displayNumber: item.displayNumber,
    viewCount: item.viewCount,
    category: null,
    requiresLogin: true,
    coverImage: image(item.coverImage, item.title),
    blocks: [
      imageBlock(
        `${item.id}-image-1`,
        "대표 이미지",
        item.coverImage,
        item.title,
        "리버스클리닉이 미디어에 소개된 장면과 핵심 메시지를 한 화면에서 확인할 수 있도록 정리했습니다.",
      ),
      textBlock(
        `${item.id}-text-1`,
        "기사 요약",
        "자연스러운 피부 탄력과 라인 개선을 위해서는 시술 자체보다 현재 피부 상태를 정확하게 파악하는 과정이 먼저라는 점을 강조했습니다. 환자 개개인의 목표와 회복 일정을 함께 고려해야 만족도가 높아집니다.",
      ),
      textBlock(
        `${item.id}-text-2`,
        "리버스클리닉 코멘트",
        "리버스클리닉은 단일 시술을 무조건 권하기보다, 상태에 맞는 강도와 간격을 정해 무리가 적은 방향으로 계획을 잡고 있습니다.",
      ),
      textBlock(
        `${item.id}-text-3`,
        "출처",
        "원문 기사와 촬영물의 출처는 각 콘텐츠 하단에 함께 표기되며, 보다 상세한 안내는 상담 시 별도로 전달드립니다.",
      ),
    ],
  }));

  const noticeItems: CommunityItem[] = noticeSeed.map((item) => ({
    id: item.id,
    boardType: "notice",
    title: item.title,
    summary: item.summary,
    author: mockAuthor,
    publishedAt: item.publishedAt,
    tags: ["공지사항"],
    isPinned: item.isPinned,
    displayNumber: item.displayNumber,
    viewCount: item.viewCount,
    category: null,
    requiresLogin: false,
    coverImage: null,
    blocks: [
      textBlock(
        `${item.id}-text-1`,
        "안내 내용",
        "홈페이지와 커뮤니티 운영 기준을 실제 안내 문구 형태로 정리한 게시글입니다. 방문 전 확인이 필요한 일정, 열람 정책, 문의 응답 기준 등을 간단하게 확인할 수 있습니다.",
      ),
      textBlock(
        `${item.id}-text-2`,
        "문의",
        "추가 문의가 필요한 경우 온라인 상담, 카카오톡 상담, 전화 상담 중 편한 방법으로 연락해 주세요.",
      ),
    ],
  }));

  return [...reviewItems, ...beforeAfterItems, ...mediaItems, ...noticeItems];
}

export function extractPopupBannerSeedsFromHomeMirror(): PopupBanner[] {
  return [
    {
      id: "popup-0",
      title: "메인 팝업 1",
      alt: "메인 팝업 1",
      href: "#",
      imageSrc: "/reverseclinic-mirror/files/6ykpMK4Lc.webp",
      mobileImageSrc: null,
      enabled: true,
      order: 0,
    },
    {
      id: "popup-1",
      title: "메인 팝업 2",
      alt: "메인 팝업 2",
      href: "#",
      imageSrc: "/reverseclinic-mirror/files/6CxBA6fdd.webp",
      mobileImageSrc: null,
      enabled: true,
      order: 1,
    },
    {
      id: "popup-2",
      title: "메인 팝업 3",
      alt: "메인 팝업 3",
      href: "#",
      imageSrc: "/reverseclinic-mirror/files/6CxByoDpl.webp",
      mobileImageSrc: null,
      enabled: true,
      order: 2,
    },
  ];
}
